I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/chapter-1.rpy", line 866, in script
    return
Exception: Could not find return label (u'game/script.rpy', 1630768831, 53).

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/chapter-1.rpy", line 866, in script
    return
  File "renpy/ast.py", line 1521, in execute
    next_node(renpy.game.context().lookup_return(pop=True))
  File "renpy/execution.py", line 710, in lookup_return
    raise Exception("Could not find return label {!r}.".format(self.return_stack[-1]))
Exception: Could not find return label (u'game/script.rpy', 1630768831, 53).

Windows-10-10.0.19041
Ren'Py 7.4.4.1439
Loraine when they shine 1.0
Sun Sep 12 15:04:29 2021
